/*
 * DO NOT ALTER/CHANGE/MODIFY
 * ALL PROPOSAL WITHOUT EXPIRY TIME WILL HOLD THE FOLLOWING VALUE OF 9999-12-31 23:59:59
 * PREVIOUS DESIGN WAS TO HOLD THE SAME TIME AS 'createTime'
 */
const constMaxDateTime = new Date('9999-12-31T23:59:59Z');

module.exports = constMaxDateTime;