/*
 * All proposal types
 */
const constProposalType = {
    UPDATE_PLAYER_INFO: "UpdatePlayerInfo",
    UPDATE_PLAYER_CREDIT: "UpdatePlayerCredit",
    UPDATE_PLAYER_REWARD_POINT: "UpdatePlayerRewardPoint",
    FIX_PLAYER_CREDIT_TRANSFER: "FixPlayerCreditTransfer",
    UPDATE_PLAYER_EMAIL: "UpdatePlayerEmail",
    UPDATE_PLAYER_PHONE: "UpdatePlayerPhone",
    UPDATE_PLAYER_QQ: "UpdatePlayerQQ",
    UPDATE_PLAYER_WECHAT: "UpdatePlayerWeChat",
    UPDATE_PLAYER_BANK_INFO: "UpdatePlayerBankInfo",
    ADD_PLAYER_REWARD_TASK: "AddPlayerRewardTask",
    UPDATE_PARTNER_BANK_INFO: "UpdatePartnerBankInfo",
    UPDATE_PARTNER_PHONE: "UpdatePartnerPhone",
    UPDATE_PARTNER_EMAIL: "UpdatePartnerEmail",
    UPDATE_PARTNER_QQ: "UpdatePartnerQQ",
    UPDATE_PARTNER_INFO: "UpdatePartnerInfo",
    FULL_ATTENDANCE: "FullAttendance",
    PLAYER_CONSUMPTION_RETURN: "PlayerConsumptionReturn",
    PARTNER_CONSUMPTION_RETURN: "PartnerConsumptionReturn",
    FIRST_TOP_UP: "FirstTopUp",
    PARTNER_INCENTIVE_REWARD: "PartnerIncentiveReward",
    PARTNER_REFERRAL_REWARD: "PartnerReferralReward",
    GAME_PROVIDER_REWARD: "GameProviderReward",
    PLATFORM_TRANSACTION_REWARD: "PlatformTransactionReward",
    PLAYER_MANUAL_TOP_UP: "ManualPlayerTopUp",
    PLAYER_ALIPAY_TOP_UP: "PlayerAlipayTopUp",
    PLAYER_WECHAT_TOP_UP: "PlayerWechatTopUp",
    PLAYER_TOP_UP: "PlayerTopUp",
    PLAYER_BONUS: "PlayerBonus",
    PLAYER_TOP_UP_RETURN: "PlayerTopUpReturn",
    PLAYER_CONSUMPTION_INCENTIVE: "PlayerConsumptionIncentive",
    PLAYER_LEVEL_UP: "PlayerLevelUp",
    PARTNER_TOP_UP_RETURN: "PartnerTopUpReturn",
    PLAYER_TOP_UP_REWARD: "PlayerTopUpReward",
    PLAYER_REFERRAL_REWARD: "PlayerReferralReward",
    PARTNER_BONUS: "PartnerBonus",
    PLAYER_CONSUMPTION_RETURN_FIX: "PlayerConsumptionReturnFix",
    PLAYER_REGISTRATION_REWARD: "PlayerRegistrationReward",
    PARTNER_COMMISSION: "PartnerCommission",
    MANUAL_UNLOCK_PLAYER_REWARD: "ManualUnlockPlayerReward",
    PLAYER_DOUBLE_TOP_UP_REWARD: "PlayerDoubleTopUpReward",
    UPDATE_PARTNER_CREDIT:"UpdatePartnerCredit",
    PLAYER_CONSECUTIVE_LOGIN_REWARD: "PlayerConsecutiveLoginReward",
    PLAYER_REGISTRATION_INTENTION: "PlayerRegistrationIntention",
    PLAYER_EASTER_EGG_REWARD: "PlayerEasterEggReward",
    PLAYER_QUICKPAY_TOP_UP: "PlayerQuickpayTopUp",
    PLAYER_TOP_UP_PROMO: "PlayerTopUpPromo",
    PLAYER_LEVEL_MIGRATION: "PlayerLevelMigration",
    PLAYER_CONSECUTIVE_CONSUMPTION_REWARD: "PlayerConsecutiveConsumptionReward",
    PLAYER_PACKET_RAIN_REWARD: "PlayerPacketRainReward",
    PLAYER_PROMO_CODE_REWARD: "PlayerPromoCodeReward",
    PLAYER_LIMITED_OFFER_INTENTION: "PlayerLimitedOfferIntention",
    PLAYER_LIMITED_OFFER_REWARD: "PlayerLimitedOfferReward",
    PLAYER_CONSECUTIVE_REWARD_GROUP: "PlayerConsecutiveRewardGroup",
    PLAYER_TOP_UP_RETURN_GROUP: "PlayerTopUpReturnGroup",
    PLAYER_RANDOM_REWARD_GROUP: "PlayerRandomRewardGroup",
    PLAYER_CONSUMPTION_REWARD_GROUP: "PlayerConsumptionRewardGroup",
    PLAYER_FREE_TRIAL_REWARD_GROUP: "PlayerFreeTrialRewardGroup"
};

module.exports = constProposalType;